In [1]:
import pandas as pd

In [ ]:
import os
import pandas as pd

DIR_PATH = "/Users/ipekoner/Desktop/f1-ml/f1-data"

def load_and_preview_csv(file_name, dir_path):
    file_path =os.path.join(dir_path, file_name)
    df = pd.read_csv(file_path)
    return df.head(), df.info(), df.describe()

filenames = [f for f in os.listdir(DIR_PATH) if f.endswith(".csv")]

data_overview = {}

for file in filenames:
    data_overview[file] = load_and_preview_csv(file, DIR_PATH)

print(data_overview.keys())

print(os.listdir(DIR_PATH))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 77 entries, 0 to 76
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   circuitId   77 non-null     int64
 1   circuitRef  77 non-null     object
 2   name        77 non-null     object
 3   location    77 non-null     object
 4   country     77 non-null     object
 5   lat         77 non-null     float64
 6   lng         77 non-null     float64
 7   alt         77 non-null     int64
 8   url         77 non-null     object
dtypes: float64(2), int64(2), object(5)
memory usage: 5.5+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 139 entries, 0 to 138
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   statusId  139 non-null    int64
 1   status    139 non-null    object
dtypes: int64(1), object(1)
memory usage: 2.3+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 575029 entries, 0 to 575028
Data columns (total 6 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   raceId        575029 non-null  int64
 1   driverId      575029 non-null  int64
 2   lap           575029 non-null  int64
 3   position      575029 non-null  int64
 4   time          575029 non-null  object
 5   milliseconds  575029 non-null  int64
dtypes: int64(5), object(1)
memory usage: 26.3+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   resultId        300 non-null    int64
 1   raceId          300 non-null    int64
 2   driverId        300 non-null    int64
 3   constructorId   300 non-null    int64
 4   number          300 non-null    int64
 5   grid            300 non-null    int64
 6   position        300 non-null    object
 7   positionText    300 non-null    object
 8   positionOrder   300 non-null    int64
 9   points          300 non-null    int64
 10  laps            300 non-null    int64
 11  time            300 non-null    object
 12  milliseconds    300 non-null    object
 13  fastestLap      300 non-null    object
 14  fastestLapTime  300 non-null    object
 15  statusId        300 non-null    int64
dtypes: int64(10), object(6)
memory usage: 37.6+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 859 entries, 0 to 858
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   driverId     859 non-null    int64
 1   driverRef    859 non-null    object
 2   number       859 non-null    object
 3   code         859 non-null    object
 4   forename     859 non-null    object
 5   surname      859 non-null    object
 6   dob          859 non-null    object
 7   nationality  859 non-null    object
 8   url          859 non-null    object
dtypes: int64(1), object(8)
memory usage: 60.5+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1125 entries, 0 to 1124
Data columns (total 18 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   raceId       1125 non-null   int64
 1   year         1125 non-null   int64
 2   round        1125 non-null   int64
 3   circuitId    1125 non-null   int64
 4   name         1125 non-null   object
 5   date         1125 non-null   object
 6   time         1125 non-null   object
 7   url          1125 non-null   object
 8   fp1_date     1125 non-null   object
 9   fp1_time     1125 non-null   object
 10  fp2_date     1125 non-null   object
 11  fp2_time     1125 non-null   object
 12  fp3_date     1125 non-null   object
 13  fp3_time     1125 non-null   object
 14  quali_date   1125 non-null   object
 15  quali_time   1125 non-null   object
 16  sprint_date  1125 non-null   object
 17  sprint_time  1125 non-null   object
dtypes: int64(4), object(14)
memory usage: 158.3+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 212 entries, 0 to 211
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   constructorId   212 non-null    int64
 1   constructorRef  212 non-null    object
 2   name            212 non-null    object
 3   nationality     212 non-null    object
 4   url             212 non-null    object
dtypes: int64(1), object(4)
memory usage: 8.4+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13261 entries, 0 to 13260
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   constructorStandingsId  13261 non-null  int64
 1   raceId                  13261 non-null  int64
 2   constructorId           13261 non-null  int64
 3   points                  13261 non-null  float64
 4   position                13261 non-null  int64
 5   positionText            13261 non-null  object
 6   wins                    13261 non-null  int64
dtypes: float64(1), int64(5), object(1)
memory usage: 725.3+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10234 entries, 0 to 10233
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   qualifyId      10234 non-null  int64
 1   raceId         10234 non-null  int64
 2   driverId       10234 non-null  int64
 3   constructorId  10234 non-null  int64
 4   number         10234 non-null  int64
 5   position       10234 non-null  int64
 6   q1             10234 non-null  object
 7   q2             10221 non-null  object
 8   q3             10207 non-null  object
dtypes: int64(6), object(3)
memory usage: 719.7+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34574 entries, 0 to 34573
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   driverStandingsId  34574 non-null  int64
 1   raceId             34574 non-null  int64
 2   driverId           34574 non-null  int64
 3   points             34574 non-null  float64
 4   position           34574 non-null  int64
 5   positionText       34574 non-null  object
 6   wins               34574 non-null  int64
dtypes: float64(1), int64(5), object(1)
memory usage: 1.8+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12495 entries, 0 to 12494
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   constructorResultsId  12495 non-null  int64
 1   raceId                12495 non-null  int64
 2   constructorId         12495 non-null  int64
 3   points                12495 non-null  float64
 4   status                12495 non-null  object
dtypes: float64(1), int64(3), object(1)
memory usage: 488.2+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10945 entries, 0 to 10944
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   raceId        10945 non-null  int64
 1   driverId      10945 non-null  int64
 2   stop          10945 non-null  int64
 3   lap           10945 non-null  int64
 4   time          10945 non-null  object
 5   duration      10945 non-null  object
 6   milliseconds  10945 non-null  int64
dtypes: int64(5), object(2)
memory usage: 598.7+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 75 entries, 0 to 74
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   year    75 non-null     int64
 1   url     75 non-null     object
dtypes: int64(1), object(1)
memory usage: 1.3+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26499 entries, 0 to 26498
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   resultId         26499 non-null  int64
 1   raceId           26499 non-null  int64
 2   driverId         26499 non-null  int64
 3   constructorId    26499 non-null  int64
 4   number           26499 non-null  object
 5   grid             26499 non-null  int64
 6   position         26499 non-null  object
 7   positionText     26499 non-null  object
 8   positionOrder    26499 non-null  int64
 9   points           26499 non-null  float64
 10  laps             26499 non-null  int64
 11  time             26499 non-null  object
 12  milliseconds     26499 non-null  object
 13  fastestLap       26499 non-null  object
 14  rank             26499 non-null  object
 15  fastestLapTime   26499 non-null  object
 16  fastestLapSpeed  26499 non-null  object
 17  statusId         26499 non-null  int64
dtypes: float64(1), int64(8), object(9)
memory usage: 3.6+ MB
dict_keys(['circuits.csv', 'status.csv', 'lap_times.csv', 'sprint_results.csv', 'drivers.csv', 'races.csv', 'constructors.csv', 'constructor_standings.csv', 'qualifying.csv', 'driver_standings.csv', 'constructor_results.csv', 'pit_stops.csv', 'seasons.csv', 'results.csv'])
['circuits.csv', '.DS_Store', 'status.csv', 'lap_times.csv', 'sprint_results.csv', 'drivers.csv', 'races.csv', 'constructors.csv', 'constructor_standings.csv', 'qualifying.csv', 'driver_standings.csv', 'constructor_results.csv', 'pit_stops.csv', 'seasons.csv', 'results.csv']

:

In [ ]:
import pandas as pd

results = pd.read_csv(os.path.join(DIR_PATH, "results.csv"))
drivers = pd.read_csv(os.path.join(DIR_PATH, "drivers.csv"))

results_subset = results[["raceId","driverId","constructorId","grid","position"]]

merged = results_subset.merge(drivers, on="driverId", how="inner")

final_df = merged[["raceId","driverId","constructorId","grid","position", "forename", "surname"]]

final_df

       raceId  driverId  constructorId  grid position  forename     surname
0          18         1              1     1        1     Lewis    Hamilton
1          18         2              2     5        2      Nick    Heidfeld
2          18         3              3     7        3      Nico     Rosberg
3          18         4              4    11        4  Fernando      Alonso
4          18         5              1     3        5    Heikki  Kovalainen
...       ...       ...            ...   ...      ...       ...         ...
26494    1131       822             15    18       16  Valtteri      Bottas
26495    1131       855             15    20       17    Guanyu        Zhou
26496    1131         4            117    15       18  Fernando      Alonso
26497    1131       858              3    19       19     Logan    Sargeant
26498    1131       846              1     2       20     Lando      Norris

[26499 rows x 7 columns]

:

In [ ]:
races = pd.read_csv(os.path.join(DIR_PATH, "races.csv"))

merged = results.merge(drivers, on="driverId", how="inner") #merging drivers to results with the key as driverId 

merged = merged.merge(races[["raceId","name", "date", "year"]], on="raceId", how="inner") #taking the merged and merging races to it with the selected columns with the key as raceId
#also, next time pls just extract the year from the date by using datetime, this is kinda stupid lmao
final_df = merged[["raceId","name", "driverId","constructorId","date", "year", "grid","position", "forename", "surname"]]

final_df

,raceId,name,driverId,constructorId,date,year,grid,position,forename,surname
0,18,Australian Grand Prix,1,1,2008-03-16,2008,1,1,Lewis,Hamilton
1,18,Australian Grand Prix,2,2,2008-03-16,2008,5,2,Nick,Heidfeld
2,18,Australian Grand Prix,3,3,2008-03-16,2008,7,3,Nico,Rosberg
3,18,Australian Grand Prix,4,4,2008-03-16,2008,11,4,Fernando,Alonso
4,18,Australian Grand Prix,5,1,2008-03-16,2008,3,5,Heikki,Kovalainen
...,...,...,...,...,...,...,...,...,...,...
26494,1131,Austrian Grand Prix,822,15,2024-06-30,2024,18,16,Valtteri,Bottas
26495,1131,Austrian Grand Prix,855,15,2024-06-30,2024,20,17,Guanyu,Zhou
26496,1131,Austrian Grand Prix,4,117,2024-06-30,2024,15,18,Fernando,Alonso
26497,1131,Austrian Grand Prix,858,3,2024-06-30,2024,19,19,Logan,Sargeant
26498,1131,Austrian Grand Prix,846,1,2024-06-30,2024,2,20,Lando,Norris

:

In [ ]:
merged["grid"] = pd.to_numeric(merged["grid"], errors = "coerce")
merged["position"] = pd.to_numeric(merged["position"], errors = "coerce")

merged["delta"] = merged["grid"] - merged["position"]

print(merged[["raceId","name", "driverId","constructorId","grid","position", "forename", "surname", "delta"]])

merged["delta"] = merged["grid"] - merged["position"]

merged

       raceId                   name  driverId  constructorId  grid  position  \
0          18  Australian Grand Prix         1              1     1       1.0
1          18  Australian Grand Prix         2              2     5       2.0
2          18  Australian Grand Prix         3              3     7       3.0
3          18  Australian Grand Prix         4              4    11       4.0
4          18  Australian Grand Prix         5              1     3       5.0
...       ...                    ...       ...            ...   ...       ...
26494    1131    Austrian Grand Prix       822             15    18      16.0
26495    1131    Austrian Grand Prix       855             15    20      17.0
26496    1131    Austrian Grand Prix         4            117    15      18.0
26497    1131    Austrian Grand Prix       858              3    19      19.0
26498    1131    Austrian Grand Prix       846              1     2      20.0

       forename     surname  delta
0         Lewis    Hamilton    0.0
1          Nick    Heidfeld    3.0
2          Nico     Rosberg    4.0
3      Fernando      Alonso    7.0
4        Heikki  Kovalainen   -2.0
...         ...         ...    ...
26494  Valtteri      Bottas    2.0
26495    Guanyu        Zhou    3.0
26496  Fernando      Alonso   -3.0
26497     Logan    Sargeant    0.0
26498     Lando      Norris  -18.0

[26499 rows x 9 columns]

,resultId,raceId,driverId,constructorId,number_x,grid,position,positionText,positionOrder,points,...,code,forename,surname,dob,nationality,url,name,date,year,delta
0,1,18,1,1,22,1,1.0,1,1,10.0,...,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton,Australian Grand Prix,2008-03-16,2008,0.0
1,2,18,2,2,3,5,2.0,2,2,8.0,...,HEI,Nick,Heidfeld,1977-05-10,German,http://en.wikipedia.org/wiki/Nick_Heidfeld,Australian Grand Prix,2008-03-16,2008,3.0
2,3,18,3,3,7,7,3.0,3,3,6.0,...,ROS,Nico,Rosberg,1985-06-27,German,http://en.wikipedia.org/wiki/Nico_Rosberg,Australian Grand Prix,2008-03-16,2008,4.0
3,4,18,4,4,5,11,4.0,4,4,5.0,...,ALO,Fernando,Alonso,1981-07-29,Spanish,http://en.wikipedia.org/wiki/Fernando_Alonso,Australian Grand Prix,2008-03-16,2008,7.0
4,5,18,5,1,23,3,5.0,5,5,4.0,...,KOV,Heikki,Kovalainen,1981-10-19,Finnish,http://en.wikipedia.org/wiki/Heikki_Kovalainen,Australian Grand Prix,2008-03-16,2008,-2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26494,26500,1131,822,15,77,18,16.0,16,16,0.0,...,BOT,Valtteri,Bottas,1989-08-28,Finnish,http://en.wikipedia.org/wiki/Valtteri_Bottas,Austrian Grand Prix,2024-06-30,2024,2.0
26495,26501,1131,855,15,24,20,17.0,17,17,0.0,...,ZHO,Guanyu,Zhou,1999-05-30,Chinese,http://en.wikipedia.org/wiki/Zhou_Guanyu,Austrian Grand Prix,2024-06-30,2024,3.0
26496,26502,1131,4,117,14,15,18.0,18,18,0.0,...,ALO,Fernando,Alonso,1981-07-29,Spanish,http://en.wikipedia.org/wiki/Fernando_Alonso,Austrian Grand Prix,2024-06-30,2024,-3.0
26497,26503,1131,858,3,2,19,19.0,19,19,0.0,...,SAR,Logan,Sargeant,2000-12-31,American,http://en.wikipedia.org/wiki/Logan_Sargeant,Austrian Grand Prix,2024-06-30,2024,0.0
26498,26504,1131,846,1,4,2,20.0,20,20,0.0,...,NOR,Lando,Norris,1999-11-13,British,http://en.wikipedia.org/wiki/Lando_Norris,Austrian Grand Prix,2024-06-30,2024,-18.0

:

In [ ]:
teams = pd.read_csv(os.path.join(DIR_PATH, "constructors.csv"))
team_points = pd.read_csv(os.path.join(DIR_PATH, "constructor_results.csv"))

team_points = team_points[["raceId", "constructorId", "points"]].rename(
    columns={"points": "constructor_points"}
)
teams = teams[["constructorId", "name"]].rename(columns={"name": "constructor_name"})



merged = merged.merge(team_points, on=["raceId", "constructorId"], how="left")
merged = merged.merge(teams, on="constructorId", how="left")


merged = merged[["raceId","date", "year","name", "driverId","constructorId","grid","position", "forename", "surname", "delta", "constructor_name", "constructor_points"]]

merged

,raceId,date,year,name,driverId,constructorId,grid,position,forename,surname,delta,constructor_name,constructor_points
0,18,2008-03-16,2008,Australian Grand Prix,1,1,1,1.0,Lewis,Hamilton,0.0,McLaren,14.0
1,18,2008-03-16,2008,Australian Grand Prix,2,2,5,2.0,Nick,Heidfeld,3.0,BMW Sauber,8.0
2,18,2008-03-16,2008,Australian Grand Prix,3,3,7,3.0,Nico,Rosberg,4.0,Williams,9.0
3,18,2008-03-16,2008,Australian Grand Prix,4,4,11,4.0,Fernando,Alonso,7.0,Renault,5.0
4,18,2008-03-16,2008,Australian Grand Prix,5,1,3,5.0,Heikki,Kovalainen,-2.0,McLaren,14.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
26494,1131,2024-06-30,2024,Austrian Grand Prix,822,15,18,16.0,Valtteri,Bottas,2.0,Sauber,0.0
26495,1131,2024-06-30,2024,Austrian Grand Prix,855,15,20,17.0,Guanyu,Zhou,3.0,Sauber,0.0
26496,1131,2024-06-30,2024,Austrian Grand Prix,4,117,15,18.0,Fernando,Alonso,-3.0,Aston Martin,0.0
26497,1131,2024-06-30,2024,Austrian Grand Prix,858,3,19,19.0,Logan,Sargeant,0.0,Williams,0.0
26498,1131,2024-06-30,2024,Austrian Grand Prix,846,1,2,20.0,Lando,Norris,-18.0,McLaren,31.0

:

In [ ]:
merged = merged.dropna(subset=["position"])

:

In [ ]:
merged = merged.copy()
merged["position"] = pd.to_numeric(merged["position"], errors = "coerce")
merged["avg_position"] =merged.groupby("driverId")["position"].transform("mean")
merged = merged[["raceId","date","year","name", "driverId","constructorId","grid","position", "forename", "surname", "delta", "constructor_name", "constructor_points", "avg_position"]]
merged

,raceId,date,year,name,driverId,constructorId,grid,position,forename,surname,delta,constructor_name,constructor_points,avg_position
0,18,2008-03-16,2008,Australian Grand Prix,1,1,1,1.0,Lewis,Hamilton,0.0,McLaren,14.0,3.576433
1,18,2008-03-16,2008,Australian Grand Prix,2,2,5,2.0,Nick,Heidfeld,3.0,BMW Sauber,8.0,8.355072
2,18,2008-03-16,2008,Australian Grand Prix,3,3,7,3.0,Nico,Rosberg,4.0,Williams,9.0,6.355932
3,18,2008-03-16,2008,Australian Grand Prix,4,4,11,4.0,Fernando,Alonso,7.0,Renault,5.0,6.344720
4,18,2008-03-16,2008,Australian Grand Prix,5,1,3,5.0,Heikki,Kovalainen,-2.0,McLaren,14.0,11.835165
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26494,1131,2024-06-30,2024,Austrian Grand Prix,822,15,18,16.0,Valtteri,Bottas,2.0,Sauber,0.0,7.389423
26495,1131,2024-06-30,2024,Austrian Grand Prix,855,15,20,17.0,Guanyu,Zhou,3.0,Sauber,0.0,13.521739
26496,1131,2024-06-30,2024,Austrian Grand Prix,4,117,15,18.0,Fernando,Alonso,-3.0,Aston Martin,0.0,6.344720
26497,1131,2024-06-30,2024,Austrian Grand Prix,858,3,19,19.0,Logan,Sargeant,0.0,Williams,0.0,15.760000
26498,1131,2024-06-30,2024,Austrian Grand Prix,846,1,2,20.0,Lando,Norris,-18.0,McLaren,31.0,7.462264

:

In [ ]:
merged.isnull().sum()

raceId                  0
date                    0
year                    0
name                    0
driverId                0
constructorId           0
grid                    0
position                0
forename                0
surname                 0
delta                   0
constructor_name        0
constructor_points    807
avg_position            0
dtype: int64

:

In [ ]:
merged["constructor_points"] = merged["constructor_points"].fillna(0)

:

In [ ]:
merged.isnull().sum()

raceId                0
date                  0
year                  0
name                  0
driverId              0
constructorId         0
grid                  0
position              0
forename              0
surname               0
delta                 0
constructor_name      0
constructor_points    0
avg_position          0
dtype: int64

:

In [ ]:
total_avg_position = merged.groupby(["driverId", "surname"])["position"].mean().reset_index()

total_avg_position = total_avg_position.rename(columns={"position": "avg_position_total"})

total_avg_position.head()

   driverId     surname  avg_position_total
0         1    Hamilton            3.576433
1         2    Heidfeld            8.355072
2         3     Rosberg            6.355932
3         4      Alonso            6.344720
4         5  Kovalainen           11.835165

:

In [ ]:
merged["constructor_points"] = pd.to_numeric(merged["constructor_points"], errors = "coerce")
merged["constructor_points_sum"] = merged.groupby("constructorId")["constructor_points"].transform("sum")

merged = merged[["raceId","date","year","name", "driverId","constructorId","grid","position", "forename", "surname", "delta", "constructor_name", "constructor_points", "avg_position","constructor_points_sum"]]


merged

,raceId,date,year,name,driverId,constructorId,grid,position,forename,surname,delta,constructor_name,constructor_points,avg_position,constructor_points_sum
0,18,2008-03-16,2008,Australian Grand Prix,1,1,1,1.0,Lewis,Hamilton,0.0,McLaren,14.0,3.576433,11966.0
1,18,2008-03-16,2008,Australian Grand Prix,2,2,5,2.0,Nick,Heidfeld,3.0,BMW Sauber,8.0,8.355072,554.0
2,18,2008-03-16,2008,Australian Grand Prix,3,3,7,3.0,Nico,Rosberg,4.0,Williams,9.0,6.355932,6302.0
3,18,2008-03-16,2008,Australian Grand Prix,4,4,11,4.0,Fernando,Alonso,7.0,Renault,5.0,6.344720,3031.0
4,18,2008-03-16,2008,Australian Grand Prix,5,1,3,5.0,Heikki,Kovalainen,-2.0,McLaren,14.0,11.835165,11966.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26494,1131,2024-06-30,2024,Austrian Grand Prix,822,15,18,16.0,Valtteri,Bottas,2.0,Sauber,0.0,7.389423,935.0
26495,1131,2024-06-30,2024,Austrian Grand Prix,855,15,20,17.0,Guanyu,Zhou,3.0,Sauber,0.0,13.521739,935.0
26496,1131,2024-06-30,2024,Austrian Grand Prix,4,117,15,18.0,Fernando,Alonso,-3.0,Aston Martin,0.0,6.344720,861.0
26497,1131,2024-06-30,2024,Austrian Grand Prix,858,3,19,19.0,Logan,Sargeant,0.0,Williams,0.0,15.760000,6302.0
26498,1131,2024-06-30,2024,Austrian Grand Prix,846,1,2,20.0,Lando,Norris,-18.0,McLaren,31.0,7.462264,11966.0

:

In [ ]:
merged["constructor_points"] = pd.to_numeric(merged["constructor_points"], errors = "coerce")
merged["constructor_points_avg"] = merged.groupby("constructorId")["constructor_points"].transform("mean")

merged = merged[["raceId","date", "year","name", "driverId","constructorId","grid","position", "forename", "surname", "delta", "constructor_name", "constructor_points", "avg_position","constructor_points_sum", "constructor_points_avg"]]


merged

,raceId,date,year,name,driverId,constructorId,grid,position,forename,surname,delta,constructor_name,constructor_points,avg_position,constructor_points_sum,constructor_points_avg
0,18,2008-03-16,2008,Australian Grand Prix,1,1,1,1.0,Lewis,Hamilton,0.0,McLaren,14.0,3.576433,11966.0,8.785609
1,18,2008-03-16,2008,Australian Grand Prix,2,2,5,2.0,Nick,Heidfeld,3.0,BMW Sauber,8.0,8.355072,554.0,4.616667
2,18,2008-03-16,2008,Australian Grand Prix,3,3,7,3.0,Nico,Rosberg,4.0,Williams,9.0,6.355932,6302.0,5.273640
3,18,2008-03-16,2008,Australian Grand Prix,4,4,11,4.0,Fernando,Alonso,7.0,Renault,5.0,6.344720,3031.0,5.751423
4,18,2008-03-16,2008,Australian Grand Prix,5,1,3,5.0,Heikki,Kovalainen,-2.0,McLaren,14.0,11.835165,11966.0,8.785609
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26494,1131,2024-06-30,2024,Austrian Grand Prix,822,15,18,16.0,Valtteri,Bottas,2.0,Sauber,0.0,7.389423,935.0,1.693841
26495,1131,2024-06-30,2024,Austrian Grand Prix,855,15,20,17.0,Guanyu,Zhou,3.0,Sauber,0.0,13.521739,935.0,1.693841
26496,1131,2024-06-30,2024,Austrian Grand Prix,4,117,15,18.0,Fernando,Alonso,-3.0,Aston Martin,0.0,6.344720,861.0,6.063380
26497,1131,2024-06-30,2024,Austrian Grand Prix,858,3,19,19.0,Logan,Sargeant,0.0,Williams,0.0,15.760000,6302.0,5.273640
26498,1131,2024-06-30,2024,Austrian Grand Prix,846,1,2,20.0,Lando,Norris,-18.0,McLaren,31.0,7.462264,11966.0,8.785609

:

In [ ]:
merged["season_avg_position"] = merged.groupby(["driverId", "year"])["position"].transform("mean")

merged = merged[["raceId","date", "year","name", "driverId","constructorId","grid","position", "forename", "surname", "delta", "constructor_name", "constructor_points", "avg_position","constructor_points_sum", "constructor_points_avg","season_avg_position"]]
merged

,raceId,date,year,name,driverId,constructorId,grid,position,forename,surname,delta,constructor_name,constructor_points,avg_position,constructor_points_sum,constructor_points_avg,season_avg_position
0,18,2008-03-16,2008,Australian Grand Prix,1,1,1,1.0,Lewis,Hamilton,0.0,McLaren,14.0,3.576433,11966.0,8.785609,4.411765
1,18,2008-03-16,2008,Australian Grand Prix,2,2,5,2.0,Nick,Heidfeld,3.0,BMW Sauber,8.0,8.355072,554.0,4.616667,6.500000
2,18,2008-03-16,2008,Australian Grand Prix,3,3,7,3.0,Nico,Rosberg,4.0,Williams,9.0,6.355932,6302.0,5.273640,10.375000
3,18,2008-03-16,2008,Australian Grand Prix,4,4,11,4.0,Fernando,Alonso,7.0,Renault,5.0,6.344720,3031.0,5.751423,5.533333
4,18,2008-03-16,2008,Australian Grand Prix,5,1,3,5.0,Heikki,Kovalainen,-2.0,McLaren,14.0,11.835165,11966.0,8.785609,6.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26494,1131,2024-06-30,2024,Austrian Grand Prix,822,15,18,16.0,Valtteri,Bottas,2.0,Sauber,0.0,7.389423,935.0,1.693841,15.600000
26495,1131,2024-06-30,2024,Austrian Grand Prix,855,15,20,17.0,Guanyu,Zhou,3.0,Sauber,0.0,13.521739,935.0,1.693841,14.800000
26496,1131,2024-06-30,2024,Austrian Grand Prix,4,117,15,18.0,Fernando,Alonso,-3.0,Aston Martin,0.0,6.344720,861.0,6.063380,10.000000
26497,1131,2024-06-30,2024,Austrian Grand Prix,858,3,19,19.0,Logan,Sargeant,0.0,Williams,0.0,15.760000,6302.0,5.273640,17.375000
26498,1131,2024-06-30,2024,Austrian Grand Prix,846,1,2,20.0,Lando,Norris,-18.0,McLaren,31.0,7.462264,11966.0,8.785609,5.000000

:

In [ ]:
merged["podium"] = (merged["position"] <= 3).astype(int)

merged["pole"] = (merged["grid"] == 1).astype(int)

merged = merged[["raceId","date", "year","name", "driverId","constructorId","grid","position", "forename", "surname", "delta", "constructor_name", "constructor_points", "avg_position","constructor_points_sum", "constructor_points_avg","season_avg_position", "podium", "pole"]]
merged

,raceId,date,year,name,driverId,constructorId,grid,position,forename,surname,delta,constructor_name,constructor_points,avg_position,constructor_points_sum,constructor_points_avg,season_avg_position,podium,pole
0,18,2008-03-16,2008,Australian Grand Prix,1,1,1,1.0,Lewis,Hamilton,0.0,McLaren,14.0,3.576433,11966.0,8.785609,4.411765,1,1
1,18,2008-03-16,2008,Australian Grand Prix,2,2,5,2.0,Nick,Heidfeld,3.0,BMW Sauber,8.0,8.355072,554.0,4.616667,6.500000,1,0
2,18,2008-03-16,2008,Australian Grand Prix,3,3,7,3.0,Nico,Rosberg,4.0,Williams,9.0,6.355932,6302.0,5.273640,10.375000,1,0
3,18,2008-03-16,2008,Australian Grand Prix,4,4,11,4.0,Fernando,Alonso,7.0,Renault,5.0,6.344720,3031.0,5.751423,5.533333,0,0
4,18,2008-03-16,2008,Australian Grand Prix,5,1,3,5.0,Heikki,Kovalainen,-2.0,McLaren,14.0,11.835165,11966.0,8.785609,6.000000,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26494,1131,2024-06-30,2024,Austrian Grand Prix,822,15,18,16.0,Valtteri,Bottas,2.0,Sauber,0.0,7.389423,935.0,1.693841,15.600000,0,0
26495,1131,2024-06-30,2024,Austrian Grand Prix,855,15,20,17.0,Guanyu,Zhou,3.0,Sauber,0.0,13.521739,935.0,1.693841,14.800000,0,0
26496,1131,2024-06-30,2024,Austrian Grand Prix,4,117,15,18.0,Fernando,Alonso,-3.0,Aston Martin,0.0,6.344720,861.0,6.063380,10.000000,0,0
26497,1131,2024-06-30,2024,Austrian Grand Prix,858,3,19,19.0,Logan,Sargeant,0.0,Williams,0.0,15.760000,6302.0,5.273640,17.375000,0,0
26498,1131,2024-06-30,2024,Austrian Grand Prix,846,1,2,20.0,Lando,Norris,-18.0,McLaren,31.0,7.462264,11966.0,8.785609,5.000000,0,0

:

In [ ]:
#check the bias and variance cost func lowkey i forgot
from sklearn.preprocessing import LabelEncoder
import pandas as pd

le = LabelEncoder()
merged["driverId_encoded"] = le.fit_transform(merged["driverId"])
merged["constructorId_encoded"] = le.fit_transform(merged["constructorId"])
merged["GP_name_encoded"] = le.fit_transform(merged["name"])

merged

#print("Category mapping:", le.classes_)

,raceId,date,year,name,driverId,constructorId,grid,position,forename,surname,...,constructor_points,avg_position,constructor_points_sum,constructor_points_avg,season_avg_position,podium,pole,driverId_encoded,constructorId_encoded,GP_name_encoded
0,18,2008-03-16,2008,Australian Grand Prix,1,1,1,1.0,Lewis,Hamilton,...,14.0,3.576433,11966.0,8.785609,4.411765,1,1,0,0,3
1,18,2008-03-16,2008,Australian Grand Prix,2,2,5,2.0,Nick,Heidfeld,...,8.0,8.355072,554.0,4.616667,6.500000,1,0,1,1,3
2,18,2008-03-16,2008,Australian Grand Prix,3,3,7,3.0,Nico,Rosberg,...,9.0,6.355932,6302.0,5.273640,10.375000,1,0,2,2,3
3,18,2008-03-16,2008,Australian Grand Prix,4,4,11,4.0,Fernando,Alonso,...,5.0,6.344720,3031.0,5.751423,5.533333,0,0,3,3,3
4,18,2008-03-16,2008,Australian Grand Prix,5,1,3,5.0,Heikki,Kovalainen,...,14.0,11.835165,11966.0,8.785609,6.000000,0,0,4,0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26494,1131,2024-06-30,2024,Austrian Grand Prix,822,15,18,16.0,Valtteri,Bottas,...,0.0,7.389423,935.0,1.693841,15.600000,0,0,619,14,4
26495,1131,2024-06-30,2024,Austrian Grand Prix,855,15,20,17.0,Guanyu,Zhou,...,0.0,13.521739,935.0,1.693841,14.800000,0,0,651,14,4
26496,1131,2024-06-30,2024,Austrian Grand Prix,4,117,15,18.0,Fernando,Alonso,...,0.0,6.344720,861.0,6.063380,10.000000,0,0,3,95,4
26497,1131,2024-06-30,2024,Austrian Grand Prix,858,3,19,19.0,Logan,Sargeant,...,0.0,15.760000,6302.0,5.273640,17.375000,0,0,654,2,4
26498,1131,2024-06-30,2024,Austrian Grand Prix,846,1,2,20.0,Lando,Norris,...,31.0,7.462264,11966.0,8.785609,5.000000,0,0,642,0,4

:

In [ ]:
merged["driver_fullname"] = merged["forename"] + " " + merged["surname"]
merged

,raceId,date,year,name,driverId,constructorId,grid,position,forename,surname,...,avg_position,constructor_points_sum,constructor_points_avg,season_avg_position,podium,pole,driverId_encoded,constructorId_encoded,GP_name_encoded,driver_fullname
0,18,2008-03-16,2008,Australian Grand Prix,1,1,1,1.0,Lewis,Hamilton,...,3.576433,11966.0,8.785609,4.411765,1,1,0,0,3,Lewis Hamilton
1,18,2008-03-16,2008,Australian Grand Prix,2,2,5,2.0,Nick,Heidfeld,...,8.355072,554.0,4.616667,6.500000,1,0,1,1,3,Nick Heidfeld
2,18,2008-03-16,2008,Australian Grand Prix,3,3,7,3.0,Nico,Rosberg,...,6.355932,6302.0,5.273640,10.375000,1,0,2,2,3,Nico Rosberg
3,18,2008-03-16,2008,Australian Grand Prix,4,4,11,4.0,Fernando,Alonso,...,6.344720,3031.0,5.751423,5.533333,0,0,3,3,3,Fernando Alonso
4,18,2008-03-16,2008,Australian Grand Prix,5,1,3,5.0,Heikki,Kovalainen,...,11.835165,11966.0,8.785609,6.000000,0,0,4,0,3,Heikki Kovalainen
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26494,1131,2024-06-30,2024,Austrian Grand Prix,822,15,18,16.0,Valtteri,Bottas,...,7.389423,935.0,1.693841,15.600000,0,0,619,14,4,Valtteri Bottas
26495,1131,2024-06-30,2024,Austrian Grand Prix,855,15,20,17.0,Guanyu,Zhou,...,13.521739,935.0,1.693841,14.800000,0,0,651,14,4,Guanyu Zhou
26496,1131,2024-06-30,2024,Austrian Grand Prix,4,117,15,18.0,Fernando,Alonso,...,6.344720,861.0,6.063380,10.000000,0,0,3,95,4,Fernando Alonso
26497,1131,2024-06-30,2024,Austrian Grand Prix,858,3,19,19.0,Logan,Sargeant,...,15.760000,6302.0,5.273640,17.375000,0,0,654,2,4,Logan Sargeant
26498,1131,2024-06-30,2024,Austrian Grand Prix,846,1,2,20.0,Lando,Norris,...,7.462264,11966.0,8.785609,5.000000,0,0,642,0,4,Lando Norris

:

In [ ]:
merged.isnull().sum()

raceId                    0
date                      0
year                      0
name                      0
driverId                  0
constructorId             0
grid                      0
position                  0
forename                  0
surname                   0
delta                     0
constructor_name          0
constructor_points        0
avg_position              0
constructor_points_sum    0
constructor_points_avg    0
season_avg_position       0
podium                    0
pole                      0
driverId_encoded          0
constructorId_encoded     0
GP_name_encoded           0
driver_fullname           0
dtype: int64

:

In [ ]:
merged = merged.copy()
merged["season_avg_delta"] = merged.groupby(["driverId", "year"])["delta"].transform("mean")
merged

,raceId,date,year,name,driverId,constructorId,grid,position,forename,surname,...,constructor_points_sum,constructor_points_avg,season_avg_position,podium,pole,driverId_encoded,constructorId_encoded,GP_name_encoded,driver_fullname,season_avg_delta
0,18,2008-03-16,2008,Australian Grand Prix,1,1,1,1.0,Lewis,Hamilton,...,11966.0,8.785609,4.411765,1,1,0,0,3,Lewis Hamilton,-0.352941
1,18,2008-03-16,2008,Australian Grand Prix,2,2,5,2.0,Nick,Heidfeld,...,554.0,4.616667,6.500000,1,0,1,1,3,Nick Heidfeld,2.500000
2,18,2008-03-16,2008,Australian Grand Prix,3,3,7,3.0,Nico,Rosberg,...,6302.0,5.273640,10.375000,1,0,2,2,3,Nico Rosberg,1.937500
3,18,2008-03-16,2008,Australian Grand Prix,4,4,11,4.0,Fernando,Alonso,...,3031.0,5.751423,5.533333,0,0,3,3,3,Fernando Alonso,1.533333
4,18,2008-03-16,2008,Australian Grand Prix,5,1,3,5.0,Heikki,Kovalainen,...,11966.0,8.785609,6.000000,0,0,4,0,3,Heikki Kovalainen,-1.666667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26494,1131,2024-06-30,2024,Austrian Grand Prix,822,15,18,16.0,Valtteri,Bottas,...,935.0,1.693841,15.600000,0,0,619,14,4,Valtteri Bottas,-1.900000
26495,1131,2024-06-30,2024,Austrian Grand Prix,855,15,20,17.0,Guanyu,Zhou,...,935.0,1.693841,14.800000,0,0,651,14,4,Guanyu Zhou,1.300000
26496,1131,2024-06-30,2024,Austrian Grand Prix,4,117,15,18.0,Fernando,Alonso,...,861.0,6.063380,10.000000,0,0,3,95,4,Fernando Alonso,-0.181818
26497,1131,2024-06-30,2024,Austrian Grand Prix,858,3,19,19.0,Logan,Sargeant,...,6302.0,5.273640,17.375000,0,0,654,2,4,Logan Sargeant,1.125000
26498,1131,2024-06-30,2024,Austrian Grand Prix,846,1,2,20.0,Lando,Norris,...,11966.0,8.785609,5.000000,0,0,642,0,4,Lando Norris,-1.363636

:

In [ ]:
merged.to_csv("f1_merged_database_new.csv")

:

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report
import warnings
warnings.filterwarnings('ignore')

X = merged[["driverId_encoded", "constructorId_encoded", "GP_name_encoded", "constructor_points_avg", "constructor_points_sum", "season_avg_position", "season_avg_delta", "grid"]]
y = merged["podium"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state= 42)

rf_classifier = RandomForestClassifier(n_estimators=100, random_state = 42)

rf_classifier.fit(X_train, y_train)

y_pred = rf_classifier.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)
print(f"Accurracy: {accuracy: .2f}")
print("\nClassification Report:", classification_rep)

sample = X_test.iloc[0:1]
prediction = rf_classifier.predict(sample)

Accurracy:  0.86

Classification Report:               precision    recall  f1-score   support

           0       0.91      0.92      0.91      2430
           1       0.70      0.67      0.68       685

    accuracy                           0.86      3115
   macro avg       0.80      0.79      0.80      3115
weighted avg       0.86      0.86      0.86      3115

:

In [ ]:

from imblearn.over_sampling import RandomOverSampler
X_class = merged[["driverId_encoded", "constructorId_encoded", "GP_name_encoded", "constructor_points_avg", "constructor_points_sum", "season_avg_position", "season_avg_delta", "grid"]]
y_class = merged["podium"]

X_train, X_test, y_train, y_test = train_test_split(X_class, y_class, test_size = 0.2, random_state=42)
sm= RandomOverSampler(random_state = 42)
X_train_res, y_train_res = sm.fit_resample(X_train, y_train)

rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42, class_weight ="balanced")
rf_classifier.fit(X_train_res, y_train_res)
y_pred = rf_classifier.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)
print(f"Accurracy: {accuracy: .2f}")
print("\nClassification Report:", classification_rep)

Accurracy:  0.86

Classification Report:               precision    recall  f1-score   support

           0       0.92      0.89      0.91      2430
           1       0.66      0.73      0.69       685

    accuracy                           0.86      3115
   macro avg       0.79      0.81      0.80      3115
weighted avg       0.86      0.86      0.86      3115

:

In [ ]:

from imblearn.over_sampling import SMOTE
X_class_1 = merged[["driverId_encoded", "constructorId_encoded", "GP_name_encoded", "constructor_points_avg", "constructor_points_sum", "season_avg_position", "season_avg_delta", "grid"]]
y_class_1 = merged["podium"]

X_train, X_test, y_train, y_test = train_test_split(X_class_1, y_class_1, test_size = 0.2, random_state=42)
ac= SMOTE(random_state = 42)
X_train_res, y_train_res = ac.fit_resample(X_train, y_train)

rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)
rf_classifier.fit(X_train_res, y_train_res)
y_pred = rf_classifier.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)
print(f"Accurracy: {accuracy: .2f}")
print("\nClassification Report:", classification_rep)

Accurracy:  0.86

Classification Report:               precision    recall  f1-score   support

           0       0.93      0.88      0.91      2430
           1       0.65      0.77      0.70       685

    accuracy                           0.86      3115
   macro avg       0.79      0.82      0.80      3115
weighted avg       0.87      0.86      0.86      3115

:

In [ ]:

from imblearn.over_sampling import SMOTE
from mlxtend.evaluate import bias_variance_decomp #apparently the dependencies are off, needs python 3.10 or something. so i dont think its gonna work UNLESS i do like a scikit-based line by line bias-variance decomp
from sklearn.ensemble import BaggingClassifier
X_class_2 = merged[["driverId_encoded", "constructorId_encoded", "GP_name_encoded", "constructor_points_avg", "constructor_points_sum", "season_avg_position", "season_avg_delta", "grid"]]
y_class_2 = merged["podium"]

X_train, X_test, y_train, y_test = train_test_split(X_class_2, y_class_2, test_size = 0.2, random_state=42)
ac= SMOTE(random_state = 42)
X_train_res, y_train_res = ac.fit_resample(X_train, y_train)

rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)
rf_classifier.fit(X_train_res, y_train_res)
y_pred = rf_classifier.predict(X_test)

avg_expected_loss, avg_bias, avg_var = bias_variance_decomp(rf_classifier, X_train, y_train, X_test, y_test, loss="0-1_loss", random_seed=23, num_rounds = 50) #clf is short for classifier

accuracy = accuracy_score(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)
print(f"Accurracy: {accuracy: .2f}")
print("\nClassification Report:", classification_rep)

print("Average expected loss:%.2f" %avg_expected_loss)
print("Average bias%.2f" %avg_bias)
print("Average variance%.2f" %avg_var)

ValueError: The bias_variance_decomp does not support pandas DataFrames yet. Please check the inputs to X_train, y_train, X_test, y_test. If e.g., X_train is a pandas DataFrame, try passing it as NumPy array via X_train=X_train.values.

:

In [ ]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error
from sklearn.metrics import r2_score 
import math

X_reg = merged[["driverId_encoded", "constructorId_encoded", "GP_name_encoded", "constructor_points_avg", "constructor_points_sum", "season_avg_position", "season_avg_delta", "grid"]]
y_reg = merged["position"]

X_train, X_test, y_train, y_test = train_test_split( X_reg, y_reg, test_size = 0.2,  random_state = 42)
rf_regressor = RandomForestRegressor(n_estimators = 300, random_state = 42, min_samples_leaf = 2,)
rf_regressor.fit(X_train, y_train)
y_pred_reg = rf_regressor.predict(X_test)

mae = mean_absolute_error(y_test, y_pred_reg)
mse = mean_squared_error(y_test, y_pred_reg)
rmse = math.sqrt(mean_squared_error(y_test, y_pred_reg))
r2 = r2_score(y_test, y_pred_reg)


print(f"MAE: {mae}")
print(f"MSE: {mse}")
print(f"RMSE: {rmse}")
print(f"r2: {r2})")

sample = X_test.iloc[0:1]
predicted_position = rf_regressor.predict(sample)[0]
print(f"Predicted finishing position: {predicted_position:.1f}")

MAE: 2.157139235967647
MSE: 8.497676432047188
RMSE: 2.9150774315697325
r2: 0.6313618686548143)
Predicted finishing position: 9.7

:

In [ ]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error
from sklearn.metrics import r2_score 
from sklearn.model_selection import RandomizedSearchCV
import math

X_reg = merged[["driverId_encoded", "constructorId_encoded", "GP_name_encoded", "constructor_points_avg", "constructor_points_sum", "season_avg_position", "season_avg_delta", "grid"]]
y_reg = merged["position"]

X_train, X_test, y_train, y_test = train_test_split( X_reg, y_reg, test_size = 0.2, random_state = 42)

param_grid = {
    'n_estimators': [50, 100],
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 5],
    'min_samples_leaf': [1, 2],
    'bootstrap': [True, False]
}

random_search = RandomizedSearchCV(estimator = RandomForestRegressor (random_state = 42), param_distributions = param_grid, n_iter = 10, cv = 3, verbose = 2, n_jobs = -1, scoring = "neg_mean_absolute_error", random_state = 42)



random_search.fit(X_train, y_train)
print(random_search.best_estimator_)

Fitting 3 folds for each of 10 candidates, totalling 30 fits
[CV] END bootstrap=False, max_depth=None, min_samples_leaf=1, min_samples_split=5, n_estimators=50; total time=   9.1s
[CV] END bootstrap=False, max_depth=None, min_samples_leaf=1, min_samples_split=5, n_estimators=50; total time=   9.2s
[CV] END bootstrap=False, max_depth=20, min_samples_leaf=1, min_samples_split=2, n_estimators=50; total time=  10.2s
[CV] END bootstrap=False, max_depth=20, min_samples_leaf=1, min_samples_split=2, n_estimators=50; total time=  10.3s
[CV] END bootstrap=False, max_depth=20, min_samples_leaf=1, min_samples_split=2, n_estimators=50; total time=  10.3s
[CV] END bootstrap=False, max_depth=None, min_samples_leaf=1, min_samples_split=5, n_estimators=100; total time=  19.4s
[CV] END bootstrap=False, max_depth=None, min_samples_leaf=1, min_samples_split=5, n_estimators=100; total time=  19.6s
[CV] END bootstrap=False, max_depth=None, min_samples_leaf=1, min_samples_split=5, n_estimators=100; total time=  19.6s
[CV] END bootstrap=False, max_depth=None, min_samples_leaf=1, min_samples_split=5, n_estimators=50; total time=  10.4s
[CV] END bootstrap=False, max_depth=None, min_samples_leaf=1, min_samples_split=2, n_estimators=50; total time=  12.0s
[CV] END bootstrap=False, max_depth=20, min_samples_leaf=1, min_samples_split=5, n_estimators=100; total time=  22.2s
[CV] END bootstrap=False, max_depth=20, min_samples_leaf=1, min_samples_split=5, n_estimators=100; total time=  22.7s
[CV] END bootstrap=False, max_depth=20, min_samples_leaf=1, min_samples_split=5, n_estimators=100; total time=  22.9s
[CV] END bootstrap=False, max_depth=10, min_samples_leaf=2, min_samples_split=2, n_estimators=100; total time=  14.4s
[CV] END bootstrap=False, max_depth=None, min_samples_leaf=1, min_samples_split=2, n_estimators=50; total time=  14.5s
[CV] END bootstrap=False, max_depth=10, min_samples_leaf=2, min_samples_split=2, n_estimators=100; total time=  14.5s
[CV] END bootstrap=False, max_depth=None, min_samples_leaf=1, min_samples_split=2, n_estimators=50; total time=  14.8s
[CV] END bootstrap=False, max_depth=10, min_samples_leaf=2, min_samples_split=2, n_estimators=100; total time=  15.5s
[CV] END bootstrap=True, max_depth=10, min_samples_leaf=2, min_samples_split=2, n_estimators=50; total time=   6.9s
[CV] END bootstrap=True, max_depth=10, min_samples_leaf=2, min_samples_split=2, n_estimators=50; total time=   8.2s
[CV] END bootstrap=True, max_depth=10, min_samples_leaf=2, min_samples_split=2, n_estimators=50; total time=   8.3s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=2, min_samples_split=2, n_estimators=50; total time=  12.9s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=2, min_samples_split=2, n_estimators=50; total time=  14.9s
[CV] END bootstrap=True, max_depth=None, min_samples_leaf=2, min_samples_split=2, n_estimators=50; total time=  14.9s
[CV] END bootstrap=True, max_depth=20, min_samples_leaf=1, min_samples_split=5, n_estimators=100; total time=  23.8s
[CV] END bootstrap=True, max_depth=20, min_samples_leaf=1, min_samples_split=5, n_estimators=100; total time=  23.7s
[CV] END bootstrap=True, max_depth=20, min_samples_leaf=1, min_samples_split=5, n_estimators=100; total time=  23.8s
[CV] END bootstrap=False, max_depth=None, min_samples_leaf=1, min_samples_split=2, n_estimators=100; total time=  26.1s
[CV] END bootstrap=False, max_depth=None, min_samples_leaf=1, min_samples_split=2, n_estimators=100; total time=  26.1s
[CV] END bootstrap=False, max_depth=None, min_samples_leaf=1, min_samples_split=2, n_estimators=100; total time=  21.4s
RandomForestRegressor(max_depth=10, min_samples_leaf=2, n_estimators=50,
                      random_state=42)

:

In [ ]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error
from sklearn.metrics import r2_score 
import math

X_reg = merged[["driverId_encoded", "constructorId_encoded", "GP_name_encoded", "constructor_points_avg", "constructor_points_sum", "season_avg_position", "season_avg_delta", "grid"]]
y_reg = merged["position"]

X_train, X_test, y_train, y_test = train_test_split( X_reg, y_reg, test_size = 0.2,  random_state = 42)
rf_regressor = RandomForestRegressor(max_depth=10, min_samples_leaf=2, n_estimators=50, random_state=42)
rf_regressor.fit(X_train, y_train)
y_pred_reg = rf_regressor.predict(X_test)

mae = mean_absolute_error(y_test, y_pred_reg)
mse = mean_squared_error(y_test, y_pred_reg)
rmse = math.sqrt(mean_squared_error(y_test, y_pred_reg))
r2 = r2_score(y_test, y_pred_reg)


print(f"MAE: {mae}")
print(f"MSE: {mse}")
print(f"RMSE: {rmse}")
print(f"r2: {r2})")

sample = X_test.iloc[0:1]
predicted_position = rf_regressor.predict(sample)[0]
print(f"Predicted finishing position: {predicted_position:.1f}")

MAE: 2.0684416533074073
MSE: 7.857860839620838
RMSE: 2.803187621194992
r2: 0.6591177412493584)
Predicted finishing position: 9.4

:

In [ ]:
#do hyperparameter tuning for randomforestregressor

: